machine:
   services:
    - docker

  timezone:
    Europe/Paris # Set the timezone

  dependencies:
  override:
    - docker build --rm=false -t PatrckBrs/Docker_Circleci_test .
    
  test:
  override:
    - docker run --rm -ti $(docker ps -a -q) /bin/bash
